name: Email Name Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 23f2004258@ds.study.iitm.ac.in
        run: echo "Hello, world!"
